### ISSUE TITLE
Can't get it to run on local machine.

### ISSUE THREAD

**Issue by pabangan** [Afischbacher/twitter-sentiment-visualizer#1]
I cloned the repository and ran it using node index.js. The Application opens, but nothing happens when I enter in hashtag data. I'm using this for a class project and any help is appreciated, thanks!

![capture](https://user-images.githubusercontent.com/32502956/47748855-c29bf180-dc59-11e8-93ba-81a885e04e84.PNG)

**Comment by Afischbacher** [comment]
Hey!
Looks to be working on heroku, can you send me a screenshot of the console. 
Looks like you may be missing some dependencies. 

Thanks,

**Comment by pabangan** [comment]
![image](https://user-images.githubusercontent.com/32502956/47752334-2a563a80-dc62-11e8-877b-d91179fc9536.png)

So as u can see, there is no error so to speak , in the console. It runs fine, but somehow doesnt work in the local machine, like the screenshot above. 
However, there are these errors we found in inspect element. 

![image](https://user-images.githubusercontent.com/32502956/47752468-87ea8700-dc62-11e8-92c4-d9c01796bb64.png)

**Comment by Afischbacher** [comment]
@pabangan 

Hey,

Looks like the angular reference was missing, you can try to pull the latest changes and serve the application.

Thanks
